packages:
  - packages/*

catalogs:
  cli:
    '@antfu/eslint-config': ^6.0.0
    '@changesets/changelog-github': ^0.5.1
    '@changesets/cli': ^2.29.7
    '@inquirer/prompts': ^7.9.0
    eslint: ^9.38.0
    lint-staged: ^16.2.5
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.9
    tsx: ^4.20.6
    typescript: ^5.9.3

  testing:
    vitest: ^3.2.4

  types:
    '@types/node': ^24.9.1

onlyBuiltDependencies:
  - simple-git-hooks
