name: Setup CI
description: Setup CI environment

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js latest
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
