name: Release

on:
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: github.repository == 'zeevenn/starter-ts-monorepo'
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
      id-token: write # to use OpenID Connect token for provenance (changesets/action)
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/ci-setup

      - name: Create Release Pull Request or Publish to NPM
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'ci(changesets): version packages'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
